services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
    # ...
    anunturi:
        class: AdminBundle\Admin\AnnouncementAdmin
        arguments: [~, AdminBundle\Entity\Announcement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Announcement }
            
#    images:
#        class: AdminBundle\Admin\ProductAdmin
#        arguments: [~, AdminBundle\Entity\Product, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Images }
            
#    blog_post:
#        class: AdminBundle\Admin\BlogPostAdmin
#        arguments: [~, AdminBundle\Entity\BlogPost, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm, label: Blog }